version: '3.8'

services:
  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    volumes:
      - .:/fastapi
    environment:
      ENVIRONMENT: "production"
    networks:
      - custom
    depends_on:
      - database

  database:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - database.env
    ports:
      - "5432:5432"
    networks:
      - custom

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - custom

networks:
  custom:
    driver: bridge

volumes:
  postgres_data:
